// Published by strontiumcorp/laravel-mfa. This file is yours — restyle freely.
//
// Adding an authenticator app, as a dialog in three steps:
//   1. Scan the QR code (on phones: "Open in authenticator app"), or enter the key.
//   2. Enter the code the app shows.
//   3. Save the recovery codes: Complete unlocks once they're copied or
//      downloaded. Without new codes (the user had them already), a short
//      "added" step instead.
// A bottom sheet on phones, a centred dialog from `sm` up. Needs only React and
// ./icons; imports no other component and knows nothing about Inertia or routes.
//
//     <MfaTotpSetupDialog
//         open={open}
//         secret={p.secret} qrSvg={p.qr_svg} otpauthUrl={p.otpauth_url}
//         onConfirm={(code) => confirm(p.id, code)} processing={processing} error={errors.code}
//         confirmed={confirmed} recoveryCodes={recoveryCodes}
//         onClose={close} onComplete={finish}
//     />
import { type KeyboardEvent, useEffect, useId, useRef, useState } from 'react';
import { MfaIconAuthenticator, MfaIconCheck, MfaIconClose, MfaIconCopy, MfaIconDownload } from './icons';

export type MfaTotpSetupDialogProps = {
    open: boolean;
    /** The base32 key, for typing in by hand. */
    secret: string;
    /**
     * The QR code as SVG markup. It is rendered as HTML, so pass only the
     * server's own output (the settings page's `qr_svg`), never user input.
     */
    qrSvg?: string | null;
    /** The otpauth:// link (`otpauth_url`): "Open in authenticator app" on phones. */
    otpauthUrl?: string | null;
    /** Called with the digits the user entered. */
    onConfirm: (code: string) => void;
    processing?: boolean;
    error?: string | null;
    /** The code was accepted: moves on to the recovery codes (or the "added" step). */
    confirmed?: boolean;
    /** Recovery codes generated by this confirmation, shown once. */
    recoveryCodes?: string[] | null;
    /** Cancel or close before the code is confirmed. */
    onClose: () => void;
    /** Complete / Done after the code is confirmed. */
    onComplete: () => void;
    /** The downloaded file's name. */
    downloadName?: string;
};

type Step = 'scan' | 'code' | 'saved';

/**
 * Copy to the clipboard, falling back to a selected textarea where the
 * Clipboard API is missing or blocked (old browsers, webviews, iframes).
 */
async function copyText(text: string): Promise<boolean> {
    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch {
        const area = document.createElement('textarea');
        area.value = text;
        area.setAttribute('readonly', '');
        area.style.position = 'fixed';
        area.style.opacity = '0';
        document.body.appendChild(area);
        area.select();
        try {
            return document.execCommand('copy');
        } catch {
            return false;
        } finally {
            area.remove();
        }
    }
}

const grouped = (key: string) => key.replace(/\s+/g, '').replace(/(.{4})(?=.)/g, '$1 ');

const PRIMARY = 'min-h-11 rounded-lg bg-gray-900 px-5 text-sm font-semibold text-white disabled:opacity-50 dark:bg-gray-100 dark:text-gray-900';
const SECONDARY =
    'min-h-11 rounded-lg border border-gray-300 bg-white px-4 text-sm font-medium text-gray-900 disabled:opacity-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100';

export default function MfaTotpSetupDialog({
    open,
    secret,
    qrSvg = null,
    otpauthUrl = null,
    onConfirm,
    processing = false,
    error = null,
    confirmed = false,
    recoveryCodes = null,
    onClose,
    onComplete,
    downloadName = 'recovery-codes.txt',
}: MfaTotpSetupDialogProps) {
    const [step, setStep] = useState<Step>('scan');
    const [code, setCode] = useState('');
    const [keyCopied, setKeyCopied] = useState(false);
    const [saved, setSaved] = useState<'copied' | 'downloaded' | null>(null);
    const [copyFailed, setCopyFailed] = useState(false);
    const panel = useRef<HTMLDivElement>(null);
    const titleId = useId();

    // A fresh start every time it opens; the last step once the code is accepted.
    useEffect(() => {
        if (open) {
            setStep('scan');
            setCode('');
            setKeyCopied(false);
            setSaved(null);
            setCopyFailed(false);
        }
    }, [open]);
    useEffect(() => {
        if (confirmed) setStep('saved');
    }, [confirmed]);

    // After a failed attempt, clear the input for the next try.
    const wasProcessing = useRef(processing);
    useEffect(() => {
        if (wasProcessing.current && !processing && error) setCode('');
        wasProcessing.current = processing;
    }, [processing, error]);

    // While open: page scroll locked, focus inside (first field or button of
    // each step), and back on the opener afterwards.
    useEffect(() => {
        if (!open) return;
        const opener = document.activeElement as HTMLElement | null;
        const overflow = document.body.style.overflow;
        document.body.style.overflow = 'hidden';

        return () => {
            document.body.style.overflow = overflow;
            opener?.focus?.();
        };
    }, [open]);
    useEffect(() => {
        if (!open) return;
        const target = panel.current?.querySelector<HTMLElement>('[data-autofocus]') ?? panel.current;
        target?.focus();
    }, [open, step]);

    if (!open) return null;

    // Recovery codes are shown once: no way out but Complete.
    const closable = step !== 'saved';
    const hasCodes = !!recoveryCodes && recoveryCodes.length > 0;

    const onKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
        if (e.key === 'Escape' && closable) {
            e.stopPropagation();
            onClose();
        }
        if (e.key !== 'Tab' || !panel.current) return;
        // Keep Tab inside the dialog.
        const focusable = Array.from(panel.current.querySelectorAll<HTMLElement>('a[href], button:not([disabled]), input:not([disabled])'));
        const first = focusable[0];
        const last = focusable[focusable.length - 1];
        if (e.shiftKey && document.activeElement === first) {
            e.preventDefault();
            last?.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
            e.preventDefault();
            first?.focus();
        }
    };

    const copyKey = async () => setKeyCopied(await copyText(secret.replace(/\s+/g, '')));

    const copyCodes = async () => {
        const ok = await copyText((recoveryCodes ?? []).join('\n'));
        setCopyFailed(!ok);
        if (ok) setSaved('copied');
    };

    const downloadCodes = () => {
        const text = `Two-factor recovery codes. Each code works once.\n\n${(recoveryCodes ?? []).join('\n')}\n`;
        const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' }));
        const a = document.createElement('a');
        a.href = url;
        a.download = downloadName;
        // In the document and revoked a moment later: Firefox cancels a download otherwise.
        document.body.appendChild(a);
        a.click();
        a.remove();
        setTimeout(() => URL.revokeObjectURL(url), 1000);
        setCopyFailed(false);
        setSaved('downloaded');
    };

    const submit = (e: { preventDefault(): void }) => {
        e.preventDefault();
        onConfirm(code);
    };

    const stepNumber = step === 'scan' ? 1 : step === 'code' ? 2 : 3;
    const steps = hasCodes || step !== 'saved' ? 3 : 2;

    return (
        // margin 0 inline: a parent's space-y-* would otherwise push the fixed overlay down.
        <div className="fixed inset-0 z-50 flex items-end justify-center bg-gray-950/50 sm:items-center sm:p-4" style={{ margin: 0 }} onKeyDown={onKeyDown}>
            <div
                ref={panel}
                role="dialog"
                aria-modal="true"
                aria-labelledby={titleId}
                tabIndex={-1}
                className="flex max-h-[100dvh] w-full flex-col overflow-y-auto rounded-t-2xl bg-white shadow-xl outline-none sm:max-h-[90vh] sm:max-w-md sm:rounded-2xl dark:bg-gray-900"
            >
                <header className="flex items-start gap-4 px-5 pt-5 sm:px-6 sm:pt-6">
                    <div className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">
                        <MfaIconAuthenticator size={24} />
                    </div>
                    <div className="min-w-0 grow space-y-1">
                        <h2 id={titleId} className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                            {step === 'scan' ? 'Set up an authenticator app' : step === 'code' ? 'Enter the code' : hasCodes ? 'Save your recovery codes' : 'Authenticator app added'}
                        </h2>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Step {Math.min(stepNumber, steps)} of {steps}
                        </p>
                    </div>
                    {closable && (
                        <button type="button" aria-label="Close" onClick={onClose} className="-mr-2 -mt-1 flex size-11 shrink-0 items-center justify-center rounded-lg text-gray-500 dark:text-gray-400">
                            <MfaIconClose size={20} />
                        </button>
                    )}
                </header>

                <div aria-hidden className="flex gap-1.5 px-5 pt-4 sm:px-6">
                    {Array.from({ length: steps }, (_, i) => (
                        <span key={i} className={`h-1 grow rounded-full ${i < stepNumber ? 'bg-gray-900 dark:bg-gray-100' : 'bg-gray-200 dark:bg-gray-700'}`} />
                    ))}
                </div>

                {step === 'scan' && (
                    <div className="space-y-5 px-5 py-5 sm:px-6">
                        <p className="text-sm text-gray-600 dark:text-gray-400">
                            Use Google Authenticator, 1Password, Authy or a similar app.
                            <span className={otpauthUrl ? 'hidden sm:inline' : undefined}> Scan this QR code with it.</span>
                            {otpauthUrl && <span className="sm:hidden"> On this phone, open it directly:</span>}
                        </p>
                        {otpauthUrl && (
                            <a href={otpauthUrl} className={`${PRIMARY} flex items-center justify-center sm:hidden`}>
                                Open in authenticator app
                            </a>
                        )}
                        {qrSvg && (
                            <div
                                role="img"
                                aria-label="QR code for your authenticator app"
                                className="mx-auto w-48 rounded-xl bg-white p-3 ring-1 ring-gray-200 dark:ring-gray-700"
                                dangerouslySetInnerHTML={{ __html: qrSvg }}
                            />
                        )}
                        <div className="space-y-2">
                            <p className="text-sm font-medium text-gray-900 dark:text-gray-100">Can't scan? Enter this key</p>
                            <div className="flex items-center gap-2">
                                <code aria-label="Setup key" className="min-w-0 grow break-words rounded-lg bg-gray-100 px-3 py-2.5 font-mono text-sm tracking-wide text-gray-900 dark:bg-gray-800 dark:text-gray-100">
                                    {grouped(secret)}
                                </code>
                                <button type="button" onClick={copyKey} className={`${SECONDARY} inline-flex shrink-0 items-center gap-2`}>
                                    <MfaIconCopy size={16} />
                                    {keyCopied ? 'Copied' : 'Copy'}
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {step === 'code' && (
                    <form id={`${titleId}-code`} onSubmit={submit} className="space-y-3 px-5 py-5 sm:px-6">
                        <label htmlFor={`${titleId}-input`} className="block text-sm text-gray-600 dark:text-gray-400">
                            Enter the 6-digit code your authenticator app shows for this account.
                        </label>
                        <input
                            id={`${titleId}-input`}
                            data-autofocus
                            aria-label="Code from your authenticator app"
                            value={code}
                            onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 10))}
                            inputMode="numeric"
                            autoComplete="one-time-code"
                            placeholder="123456"
                            className="min-h-14 w-full rounded-lg border border-gray-300 px-4 text-center font-mono text-2xl tracking-[0.4em] dark:border-gray-700 dark:bg-gray-950 dark:text-gray-100"
                        />
                        {error && (
                            <p role="alert" className="text-sm text-red-600">
                                {error}
                            </p>
                        )}
                    </form>
                )}

                {step === 'saved' && hasCodes && (
                    <div className="space-y-4 px-5 py-5 sm:px-6">
                        <p className="text-sm text-gray-600 dark:text-gray-400">
                            If you lose your phone, sign in with one of these. Each works once, and they won't be shown again.
                        </p>
                        <ul aria-label="Recovery codes" className="grid grid-cols-2 gap-x-6 gap-y-1.5 rounded-xl bg-gray-100 p-4 font-mono text-sm text-gray-900 dark:bg-gray-800 dark:text-gray-100">
                            {recoveryCodes!.map((c) => (
                                <li key={c}>{c}</li>
                            ))}
                        </ul>
                        <div className="grid grid-cols-2 gap-2">
                            <button type="button" data-autofocus onClick={copyCodes} className={`${SECONDARY} inline-flex items-center justify-center gap-2`}>
                                <MfaIconCopy size={16} />
                                {saved === 'copied' ? 'Copied' : 'Copy'}
                            </button>
                            <button type="button" onClick={downloadCodes} className={`${SECONDARY} inline-flex items-center justify-center gap-2`}>
                                <MfaIconDownload size={16} />
                                {saved === 'downloaded' ? 'Downloaded' : 'Download'}
                            </button>
                        </div>
                        {copyFailed && (
                            <p role="alert" className="text-sm text-red-600">
                                Couldn't copy here. Download the codes instead.
                            </p>
                        )}
                    </div>
                )}

                {step === 'saved' && !hasCodes && (
                    <div className="flex items-center gap-3 px-5 py-5 sm:px-6">
                        <span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300">
                            <MfaIconCheck size={16} />
                        </span>
                        <p className="text-sm text-gray-600 dark:text-gray-400">Signing in now asks for a code from your authenticator app.</p>
                    </div>
                )}

                <footer className="mt-auto flex flex-col-reverse gap-2 border-t border-gray-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-end sm:px-6 dark:border-gray-800">
                    {step === 'scan' && (
                        <>
                            <button type="button" onClick={onClose} className={SECONDARY}>
                                Cancel
                            </button>
                            <button type="button" data-autofocus={otpauthUrl ? undefined : true} onClick={() => setStep('code')} className={PRIMARY}>
                                Next
                            </button>
                        </>
                    )}
                    {step === 'code' && (
                        <>
                            <button type="button" onClick={() => setStep('scan')} className={SECONDARY}>
                                Back
                            </button>
                            <button type="submit" form={`${titleId}-code`} disabled={processing || code.length < 6} className={PRIMARY}>
                                Confirm
                            </button>
                        </>
                    )}
                    {step === 'saved' && (
                        <>
                            {hasCodes && !saved && <p className="text-center text-xs text-gray-500 sm:mr-auto sm:text-left dark:text-gray-400">Copy or download your codes to finish.</p>}
                            <button type="button" data-autofocus={hasCodes ? undefined : true} disabled={hasCodes && !saved} onClick={onComplete} className={PRIMARY}>
                                {hasCodes ? 'Complete' : 'Done'}
                            </button>
                        </>
                    )}
                </footer>
            </div>
        </div>
    );
}
